### ISSUE TITLE
Not asking for help, just data dumping.

### ISSUE THREAD

**Issue by MilkPiggies** [astei/lazydfu#26]
LazyDFU seems to interfere with mods that replace blocks in minecraft, as in minecraft:copper gets turned into modname:copper. Not an issue, il just remove it for now but felt like sending feedback.  

Info:
MC Version: 1.16.5
Forge Verson: 36.2.39

Traceback:
[02.09 08:57:29] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector create$replaceBuilder(I)Lcom/mojang/datafixers/DataFixerBuilder; in lazydfu.mixins.json:SchemasMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap lazydfu.refmap.json

[02.09 08:57:29] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)

[02.09 08:57:29] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)

[02.09 08:57:29] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)

[02.09 08:57:29] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)

[02.09 08:57:29] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)

[02.09 08:57:29] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)

[02.09 08:57:29] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)

[02.09 08:57:29] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)

[02.09 08:57:29] [Server] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	... 38 more

**Comment by astei** [comment]
This is not a bug in my mod (this is for Fabric) and you didn't even include the full stack trace

**Comment by MilkPiggies** [comment]
wasn't using fabric but ok!
